dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}

dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.2.1

compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1'


networks:
  rinkeby:
    verify: True
    price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'

  mainnet-fork:
    verify: False
    price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'


  ganache-local:
    verify: False


  development:
    verify: False